### ISSUE TITLE
status_id isn't returned for async_doc creation

### ISSUE THREAD

**Issue by ahoward** [DocRaptor/docraptor-ruby#12] opened 2017-01-23 08:01 UTC
because:

![](https://cl.ly/irJm/Image%202017-01-23%20at%2012.55.27%20AM.png)

![](https://cl.ly/iquB/Image%202017-01-23%20at%201.00.24%20AM.png)

the string/symbol issues this lib is playing with are deadly/mind-binding ;-/

https://github.com/ahoward/map is a fix if uses generally but a re-work, i'll create a PR tomorrow

root cause seems to be:

![](https://cl.ly/irMF/Image%202017-01-23%20at%201.05.03%20AM.png)

even tho

![](https://cl.ly/irJp/Image%202017-01-23%20at%201.06.54%20AM.png)

**Comment by ahoward** [comment] 2017-01-23 16:16
i've looker farther and this is caused by a

```ruby
require 'yajl/json_gem'
```

this is the only place in the code that requires this functionality and the responses are teeny, it would be much, much safter if the returned hash was converted, via map.rb or perhaps hash_with_indifferent_access from AS, vs relying on the option :sumbolize_keys - which may or may work and which, when it fails, fails silently.

**Comment by janxious** [comment] 2017-08-09 15:37
@ahoward Is yajl something you're using in your application? I can't find any reference to it in the gem codebase. We are working from a client generation suite called [swagger](https://github.com/swagger-api/swagger-codegen), which makes patching things in the code directly difficult, since the next time it is run the changes are likely to be lost.

Anyway, to your point, what version of yajl and the DR gem was causing the issue? It is pretty easy to set up a test repo and see if it can be reproduced.

Sorry for the very late reply!

**Comment by janxious** [comment] 2017-08-28 15:42
@ahoward Again sorry it took so long for the initial reply. If you still have those details handy I asked for, drop them here. I will close this until you come back to it.

**Closed as completed by janxious** 2017-08-28 15:42 UTC
